---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waalstate_chatbot
  labels:
    app: waalstate_chatbot
spec:
  replicas: 5
  selector:
    matchLabels:
      app: waalstate_chatbot
  template:
    metadata:
      labels:
        app: waalstate_chatbot
    spec:
      containers:
        - name: waalstate_chatbot
          image: rinmeister/p3-cyber-waalstate_chatbot:latest
          ports:
            - containerPort: 4242
---

