---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: p3-waalstate_chatbot
  name: waalstate_chatbot
  labels:
    app: waalstate_chatbot
spec:
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 4242
      targetPort: 4242
  selector:
    app: waalstate_chatbot
---
