---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: p3-waalstate-chatbot
  name: waalstate-chatbot
  labels:
    app: waalstate-chatbot
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4242
      targetPort: 4242
  selector:
    app: waalstate-chatbot
---
